import nodemailer from 'nodemailer';
import { config } from '../config/config.js';
import logger from '../utils/logger.js';

const transporter = nodemailer.createTransport({
  host: config.smtp.host,
  port: config.smtp.port,
  secure: false, // Use TLS or adjust as needed for your specific SMTP provider
  auth: {
    user: config.smtp.user,
    pass: config.smtp.pass
  }
});

export const sendReportEmail = async ({ type, callerId, confirmedPhone, details }) => {
  if (!config.email.notificationEmail) {
    logger.warn('Notification email not configured. Skipping email report.');
    return;
  }

  const isSuccess = type === 'SUCCESS';
  const emoji = isSuccess ? '🟢' : '🟠';
  const subjectType = isSuccess ? 'SUCCESS' : 'REPORT';
  const subject = `${emoji} ${subjectType}: Call Interaction Report`;

  const htmlContent = `
    <h2>Call Interaction Report</h2>
    <p><strong>Status:</strong> ${subjectType}</p>

    <h3>Phone Comparison</h3>
    <ul>
      <li><strong>Original Caller ID (Twilio):</strong> ${callerId || 'Unknown'}</li>
      <li><strong>Verbally Confirmed Phone:</strong> ${confirmedPhone || 'N/A'}</li>
    </ul>

    <h3>Interaction Details</h3>
    <pre style="background: #f4f4f4; padding: 15px; border-radius: 5px; font-family: monospace;">${JSON.stringify(details, null, 2)}</pre>

    <hr />
    <p><em>Generated by 1Wire AI Cold Caller (Sarah)</em></p>
  `;

  try {
    await transporter.sendMail({
      from: `"Sarah (1Wire Assistant)" <${config.smtp.user}>`,
      to: config.email.notificationEmail,
      subject: subject,
      html: htmlContent
    });
    logger.info(`Email report sent successfully. Type: ${type}`);
  } catch (error) {
    logger.error('Error sending email report:', error);
  }
};
