import nodemailer from 'nodemailer';
import { config } from '../config/config.js';
import logger from '../utils/logger.js';

let transporter = null;

if (config.email.smtpHost && config.email.smtpUser) {
    transporter = nodemailer.createTransport({
        host: config.email.smtpHost,
        port: parseInt(config.email.smtpPort, 10),
        secure: parseInt(config.email.smtpPort, 10) === 465,
        auth: {
            user: config.email.smtpUser,
            pass: config.email.smtpPass
        }
    });
}

export const sendNotification = async (type, details) => {
    if (!transporter || !config.email.notificationEmail) {
        logger.warn('Email service is not configured. Skipping notification.');
        return;
    }

    let subject = '';
    let html = '';

    if (type === 'SUCCESS') {
        subject = `🟢 SUCCESS: Technical Assessment Scheduled - ${details.companyName}`;
        html = `
            <h2>New Technical Assessment Scheduled!</h2>
            <p><strong>Contact Name:</strong> ${details.contactName}</p>
            <p><strong>Company Name:</strong> ${details.companyName}</p>
            <p><strong>Confirmed Phone:</strong> ${details.confirmedPhone}</p>
            <p><strong>Original Caller ID:</strong> ${details.callerId}</p>
            <p><strong>Appointment Time:</strong> ${details.appointmentTime}</p>
            <hr />
            <p><em>This lead was generated by Sarah, the 1Wire AI Assistant.</em></p>
        `;
    } else if (type === 'REPORT') {
        subject = `🟠 REPORT: Interaction Log - ${details.reason || 'Not Interested/Voicemail'}`;
        html = `
            <h2>Interaction Report</h2>
            <p><strong>Outcome:</strong> ${details.reason || 'N/A'}</p>
            <p><strong>Original Caller ID:</strong> ${details.callerId}</p>
            <p><strong>Details/Notes:</strong> ${details.notes || 'No notes provided.'}</p>
            <hr />
            <p><em>This report was generated by Sarah, the 1Wire AI Assistant.</em></p>
        `;
    }

    try {
        await transporter.sendMail({
            from: `"1Wire AI System" <${config.email.smtpUser}>`,
            to: config.email.notificationEmail,
            subject,
            html
        });
        logger.info(`Notification email sent: [${type}]`);
    } catch (error) {
        logger.error(`Error sending email notification: ${error}`);
    }
};
