import nodemailer from 'nodemailer';
import { config } from '../config/config.js';
import logger from '../utils/logger.js';

let transporter = null;

if (config.email.smtpHost && config.email.smtpPort && config.email.smtpUser && config.email.smtpPass) {
  transporter = nodemailer.createTransport({
    host: config.email.smtpHost,
    port: config.email.smtpPort,
    secure: config.email.smtpPort === '465', // true for 465, false for other ports
    auth: {
      user: config.email.smtpUser,
      pass: config.email.smtpPass,
    },
  });
}

export const sendEmailReport = async (subjectPrefix, callerId, confirmedPhone, details) => {
  if (!transporter) {
    logger.warn('Email service not configured. Skipping email report.');
    return;
  }

  const subject = `${subjectPrefix} - 1Wire Sarah Interaction Report`;

  let html = `
    <h2>Sarah Interaction Report</h2>
    <p><strong>Caller ID (Twilio):</strong> ${callerId}</p>
    <p><strong>Confirmed Phone (Verbal):</strong> ${confirmedPhone}</p>
    <hr/>
    <h3>Details:</h3>
    <ul>
  `;

  for (const [key, value] of Object.entries(details)) {
    html += `<li><strong>${key}:</strong> ${value}</li>`;
  }

  html += `</ul><br/><p>Generated by 1Wire Assistant (Sarah)</p>`;

  try {
    const info = await transporter.sendMail({
      from: `"1Wire Assistant" <${config.email.smtpUser}>`,
      to: config.email.notificationEmail,
      subject: subject,
      html: html,
    });
    logger.info(`Email report sent: ${info.messageId}`);
  } catch (error) {
    logger.error('Error sending email report:', error);
  }
};
